production.c File Reference
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include `production.h`
#include <math.h>
#include <string.h>
Functions
bool production (int argc, char *argv[])
void numRowsAndCols (FILE *fp, int *numRowsInFile, int *numColsInFile)
void initializeArray (char *A, char *filename, int nRows, int nCols, int numRowsInFile, int numColsInFile)
void PlayOne (unsigned int nr, unsigned int nc, char *Old, char *New)
char getLetter (int row, int col, int nCols, char *Old)
int HowManyNeighbors (int row, int col, int nRows, int nCols, char *Old)
int generate (int gens, int nRows, int nCols, char *old_p, char *new_p, char *other_p, char print, char pause)
bool anyX (char *arr, int nRows, int nCols)
bool sameContent (char *one_p, char *another_p, int nRows, int nCols)
void printThis (int nRows, int nCols, char *old_p)
Function Documentation
anyX()
bool anyX (char * arr, int nRows, int nCols)
Determines if any organisms are still alive
Parameters
arr Array of organisms
nRows Number of rows in array
nCols Number of columns in array
Returns
true if organisms (x's) are present; false if no organisms (x's) are present
Referenced by generate(), and testAnyX().
generate()
int generate (int gens, int nRows, int nCols, char * old_p, char * new_p, char * other_p, char print, char pause)
Generates a new generation & checks for stopping conditions
Parameters
gens Maximum generations to play game
nRows Number of rows in the arrays
nCols Number of columns in the arrays
old_p Pointer to the previous generation
new_p Pointer to the current generation
other_p Pointer to two generations ago
print Determines if each generation should be printed: 'y' for yes, 'n' for no
pause Determines if there should be a pause between generations: 'y' for yes, 'n' for no
Returns
Number of generations played
References anyX(), PlayOne(), printThis(), and sameContent().
Referenced by production(), testGenerate(), testGenerate2(), and testGenerate3().
getLetter()
char getLetter (int row, int col, int nCols, char * Old)
Gets a letter from an array
Parameters
row Row to retrieve the letter from
col Column to retrieve the letter from
nCols Number of columns in the array
Old Pointer to the array
Returns
a letter
Referenced by HowManyNeighbors(), PlayOne(), and testGetLetter().
HowManyNeighbors()
int HowManyNeighbors (int row, int col, int nRows, int nCols, char * Old)
Determines the number of neighbors (x's) surrounding a cell
Parameters
row Row that cell is located in
col Column that cell is located in
nRows Number of rows in the array
nCols Number of columns in the array
Old Pointer to the array
Returns
number of neighbors (x's) surrounding a cell
References getLetter().
Referenced by PlayOne(), and testHowManyNeighbors().
initializeArray()
void initializeArray (char * A, char * filename, int nRows, int nCols, int numRowsInFile, int numColsInFile)
Creates the initial generation
Parameters
A Array to be initialized
filename Pointer to filename of the input file
nRows Number of rows on the board
nCols Number of columns on the board
numRowsInFile Number of rows in the file
numColsInFile Number of columns in the file
Referenced by production(), and testInitializeArray().
numRowsAndCols()
void numRowsAndCols (FILE * fp, int * numRowsInFile, int * numColsInFile)
Calculates the number or rows and columns in the input file
Parameters
fp Pointer to the input file
numRowsInFile Pointer to the variable that stores the number of rows in the input file
numColsInFile Pointer to the variable that stores the number of columns in the input file
Referenced by production(), and testNumRowsAndCols().
PlayOne()
void PlayOne (unsigned int nr, unsigned int nc, char * Old, char * New)
PlayOne carries out one generation
Parameters
nr Number of rows in the petri dish
nc Number of columns in the petri dish
Old Location of the upper left of starting petri dish
New Location of the upper left of the ending petri dish
References getLetter(), and HowManyNeighbors().
Referenced by generate(), testPlayOne(), and testPlayOne2().
printThis()
void printThis (int nRows, int nCols, char * old_p)
Prints the x's in the array
Parameters
nRows Number of rows in the array
nCols Number of columns in the array
old_p Pointer to the array to be printed
Referenced by generate(), and production().
production()
bool production (int argc, char * argv[])
Main production code. Reads arguments from the command line.
Parameters
argc Number of words on the command line
argv Array of pointers to character strings representing the words on the command line
Returns
true if the game was able to be played; false if the user entered bad input
References generate(), initializeArray(), numRowsAndCols(), and printThis().
Referenced by main().
sameContent()
bool sameContent (char * one_p, char * another_p, int nRows, int nCols)
Determines if two arrays are identical
Parameters
one_p Pointer to one array
another_p Pointer to a second array
nRows Number of rows in the array
nCols Number of columns in the array
Returns
true if both arrays are identical; false if there is a difference in the arrays
Referenced by generate(), and testsSameContent().