tests.c File Reference
#include <stdbool.h>
#include `tests.h`
#include `production.h`
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
bool tests (void)
bool testReadInput (void)
bool testMakeArrays (void)
bool testPlayOne (void)
bool testNumRowsAndCols (void)
bool testInitializeArray (void)
bool testPlayOne2 (void)
bool testGetLetter (void)
bool testHowManyNeighbors (void)
bool testGenerate (void)
bool testGenerate2 (void)
bool testGenerate3 (void)
bool testAnyX (void)
bool testsSameContent (void)
Function Documentation
testAnyX()
bool testAnyX (void)
Tests anyX
Returns
true if correctly identifies if there are x's in array; false otherwise
References anyX().
Referenced by tests().
testGenerate()
bool testGenerate (void)
Tests generate, terminates with all dead
Returns
true if a generations are generated correctly and game stops properly; false otherwise
References generate().
Referenced by tests().
testGenerate2()
bool testGenerate2 (void)
Tests generate method with blinker, terminates with repetition
Returns
true if a generations are generated correctly and game stops properly; false otherwise
References generate().
Referenced by tests().
testGenerate3()
bool testGenerate3 (void)
Tests generate with acorn, terminates with max generations reached
Returns
true if a generations are generated correctly and game stops properly; false otherwise
References generate().
Referenced by tests().
testGetLetter()
bool testGetLetter (void)
Tests getLetter
Returns
true if gets correct letter; false otherwise
References getLetter().
Referenced by tests().
testHowManyNeighbors()
bool testHowManyNeighbors (void)
Tests howManyNeighbors
Returns
true if gets correct number of neighbors; false otherwise
References HowManyNeighbors().
Referenced by tests().
testInitializeArray()
bool testInitializeArray (void)
Tests initializeArray method with acorn.txt
Returns
true if number rows and columns calculated correctly; false otherwise
References initializeArray().
Referenced by tests().
testMakeArrays()
bool testMakeArrays (void)
Tests that an array can be copied
Returns
true if array is successfully copied; false otherwise
Referenced by tests().
testNumRowsAndCols()
bool testNumRowsAndCols (void)
Tests numRowsAndCols method with acorn.txt
Returns
true if number rows and columns calculated correctly; false otherwise
References numRowsAndCols().
Referenced by tests().
testPlayOne()
bool testPlayOne (void)
Tests a still life pattern
Returns
true if final board is the same as the initial board; false otherwise
References PlayOne().
Referenced by tests().
testPlayOne2()
bool testPlayOne2 (void)
Tests PlayOne
Returns
true if one generation completed correctly; false otherwise
References PlayOne().
Referenced by tests().
testReadInput()
bool testReadInput (void)
Tests that input can be read
Returns
true if input can be read; false otherwise
Referenced by tests().
tests()
bool tests (void)
Main Test method
Returns
true if all tests passes; false otherwise
References testAnyX(), testGenerate(), testGenerate2(), testGenerate3(), testGetLetter(), testHowManyNeighbors(), testInitializeArray(), testMakeArrays(), testNumRowsAndCols(), testPlayOne(), testPlayOne2(), testReadInput(), and testsSameContent().
Referenced by main().
testsSameContent()
bool testsSameContent (void)
Tests sameContent
Returns
true if correctly identifies if two arrays are identical in content; false otherwise
References sameContent().
Referenced by tests().